name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add Ruby setup for better dependency control
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      # Resolve Liquid 't' tag error by installing jekyll-i18n
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle add jekyll-i18n faraday-retry
          bundle install

      # Custom Jekyll build to support plugins
      - name: Build with Jekyll
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: ./
          jekyll_cfg: |
            plugins:
              - jekyll-multiple-languages-plugin
              - jekyll-feed
              - jekyll-sitemap
              - jekyll-redirect-from
              - jekyll-paginate
              - jekyll-gist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4